### PR TITLE
MNT: Re-rendered with conda-smithy 2.1.1

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/conda-build-all-feedstock/issues/27

### CODE REVIEW

**Comment by jakirkham** [comment]
Wow! It appears the test phase is a total mess. Any ideas @msarahan? I'm at a total loss.

**Comment by jakirkham** [comment]
```python
(C:\bld\conda-build-all_1489505697904\_t_env) C:\bld\conda-build-all_1489505697904\test_tmp>conda build-all --version 
Traceback (most recent call last):
  File "C:\bld\conda-build-all_1489505697904\_t_env\Scripts\conda-build-all-script.py", line 3, in <module>
    import conda_build_all.cli
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\conda_build_all\cli.py", line 8, in <module>
    import conda_build_all.builder
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\conda_build_all\builder.py", line 20, in <module>
    from binstar_client.utils import get_binstar
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\binstar_client\__init__.py", line 14, in <module>
    from .utils import compute_hash, jencode, pv
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\binstar_client\utils\__init__.py", line 153, in <module>
    SITE_CONFIG = join(dirs.site_data_dir, 'config.yaml')
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\binstar_client\utils\appdirs.py", line 250, in site_data_dir
    version=self.version)
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\binstar_client\utils\appdirs.py", line 107, in site_data_dir
    path = os.path.join(_get_win_folder("CSIDL_COMMON_APPDATA"),
  File "C:\bld\conda-build-all_1489505697904\_t_env\lib\site-packages\binstar_client\utils\appdirs.py", line 285, in _get_win_folder_with_pywin32
    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
```

**Comment by jakirkham** [comment]
Do you have any idea what is happening here, @nicoddemus?

**Comment by msarahan** [comment]
Not sure if updating anaconda-client might help?  Seems like CSIDL paths are the problem.  Those are deprecated: https://msdn.microsoft.com/en-us/library/windows/desktop/bb762494(v=vs.85).aspx

I recommend opening an issue on the anaconda-client repo if updating doesn't help.

**Comment by jakirkham** [comment]
Trying that too. ( https://github.com/conda-forge/anaconda-client-feedstock/pull/6 )

Though it looks like this is coming from `appdirs`, which appears to not have changed in their repo for 2yrs? Do they have their own vendored copy of the Python library or does this just happen to have the same name?

**Comment by jakirkham** [comment]
Thanks @msarahan.

**Comment by jakirkham** [comment]
Seems we were blocked building `anaconda-client`. Have raised that build issue upstream already as issue ( https://github.com/Anaconda-Platform/anaconda-client/issues/398 ). Though have opted to raise this issue upstream as well in issue ( https://github.com/Anaconda-Platform/anaconda-client/issues/399 ).

**Comment by jakirkham** [comment]
Seems this issue goes away when we pin to `conda-build` 2.1.4. Should we raise an issue upstream?

**Pull request merged**
